In [1]:
def get_numbers():
    return [1, 2, 3]

def get_numbers_gen():
    yield 1
    yield 2
    yield 3

In [2]:
get_numbers()

[1, 2, 3]

In [6]:
next(get_numbers_gen())

1

In [7]:
def countdown(n):
    while n >= 0:
        yield n
        n -= 1

In [26]:
c = countdown(5)

In [ ]:
for i in c:
    print(i)

5
4
3
2
1
0

In [19]:
c

In [28]:
import sys

In [29]:
my_list = [x for x in range(10000)]

In [35]:
my_gen = (x for x in range(10000))

In [36]:
print("List size:", sys.getsizeof(my_list))
print("Generator size:", sys.getsizeof(my_gen))

List size: 85176
Generator size: 192

In [37]:
my_gen

In [39]:
def infinite_evens():
    num = 0
    while True:
        yield num
        num += 2
        
inf_gen = infinite_evens()

count = 0
for i in inf_gen:
    print(i)
    count += 1
    if count >= 5:
        break

0
2
4
6
8

In [46]:
def count_up_to(n):
    start = 0
    while start < n:
        start += 1
        yield start
        
def squared(numbers):
    for n in numbers:
        yield n * n

In [47]:
cn = count_up_to(5)
sn = squared(cn)

for c in sn:
    print(c)

1
4
9
16
25

In [48]:
log_data = [
    "INFO: User logged in\n",
    "ERROR: DB Connection Failed\n",
    "INFO: User clicked button\n",
    "ERROR: Timeout 404\n",
    "DEBUG: Variable set to 5\n"
]

In [49]:
def read_lines(data):
    for line in data:
        yield line
        
def filter_lines(lines):
    for line in lines:
        if line.startswith("ERROR"):
            yield line
            
def clean_lines(lines):
    for line in lines:
        yield line.strip('\n')

In [50]:
rlg = read_lines(log_data)
flg = filter_lines(rlg)
clg = clean_lines(flg)

In [51]:
for c in clg:
    print(c)

ERROR: DB Connection Failed
ERROR: Timeout 404

In [52]:
import pandas as pd

In [55]:
data = {
    'name': ['Tanishq', 'Arnoe', 'Tanishq'],
    'money': [28, 32, 2]
}

In [56]:
df = pd.DataFrame(data)
df

      name  money
0  Tanishq     28
1    Arnoe     32
2  Tanishq      2

In [62]:
# df.groupby(by='name')['money'].sum()
# df.groupby(by='name')['money'].agg(['min', 'max', 'sum'])
df.groupby(by='name')['money'].transform('sum')

0    30
1    32
2    30
Name: money, dtype: int64

In [68]:
import pandas as pd
import numpy as np

data = {
    'Department': ['Electronics', 'Electronics', 'Clothing', 'Clothing', 'Clothing', 'Furniture', 'Furniture'],
    'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
    'Revenue': [5000, 6000, 2000, 2500, 4000, 10000, 8000],
    'Hours': [40, 45, 30, 35, 40, 50, 48]
}

df = pd.DataFrame(data)
df['Region'] = ['North', 'North', 'South', 'North', 'South', 'South', 'North']
print(df)

    Department Salesperson  Revenue  Hours Region
0  Electronics       Alice     5000     40  North
1  Electronics         Bob     6000     45  North
2     Clothing     Charlie     2000     30  South
3     Clothing       David     2500     35  North
4     Clothing         Eve     4000     40  South
5    Furniture       Frank    10000     50  South
6    Furniture       Grace     8000     48  North

In [69]:
df['total'] = df.groupby('Department')['Revenue'].transform('max')
df

    Department Salesperson  Revenue  Hours Region  total
0  Electronics       Alice     5000     40  North   6000
1  Electronics         Bob     6000     45  North   6000
2     Clothing     Charlie     2000     30  South   4000
3     Clothing       David     2500     35  North   4000
4     Clothing         Eve     4000     40  South   4000
5    Furniture       Frank    10000     50  South  10000
6    Furniture       Grace     8000     48  North  10000

In [72]:
pivot = df.pivot_table(
    values='Revenue',
    index='Department',
    columns='Region',
    aggfunc='sum',
    fill_value=0
    )
pivot

Region       North  South
Department
Clothing      2500   6000
Electronics  11000      0
Furniture     8000  10000